apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
  labels:
    name: my-pod1
    description: this-is-label-example
    label-is-not-strict: you-can-change-label-name
  annotations:
    annotation-key1: annotation-value
    annotation-key2: very long annotation value, bla bla bla bla bla bla
spec:
  containers:
  - name: hello-world
    image: amira/nodejs-job
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"

# 2. Command apply pod:
# kuebctl apply -f 2-create-pod.yaml

# 4. Command menampilkan semua deployment/pod
# kubectl get deployments
# kubectl get pod

# 3. Command menampilkan detail pod dan deployment:
# kubectl describe pod <nama-pod>
# kubectl describe deployment <nama-deployment>

# 5. delete pod
# kubectl delete pod my-pod1

# get detail pods (IP and other)
# kubectl get pod -o wide

# access pod, just to test
# kubectl port-forward namapod portForwarded:portInternal
# example: 
# kubectl port-forward my-app-deployment1-7dbbf56bbf-dt6r4 9191:8080
# access at localhost:9191

# get pods with label
# kubectl get pods --show-labels

# search pods with query label
# kubectl get pods -l app
# kubectl get pods -l '!app' --show-labels

# delete pod with label (key=value)
# kubectl delete pod -l environment=development