apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx # should match to template
  template:
    metadata:
      name: nginx # rc will create unique code
      labels:
       app: nginx # should match to selector
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

# run
# kubectl apply -f 12-replication-controller.yaml 

# show
# kubectl get rc

# remove
# kubectl delete rc nginx-rc

# remove without deleting pod
# kubectl delete rc nginx-rc --cascade=orphan