apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-job
spec:
  completions: 4 # how much jobs runs until complete, default 1
  parallelism: 2 # how much pods running at the time, default 1
  # means it will run 2-2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nodejs-job
          image: amira/nodejs-job

# kubectl apply -f 15-create-job.yaml

# kubectl get jobs