apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodejs-cronjob
  labels:
    name: nodejs-cronjob
spec:
  nodeSelector:
    gpu: "true"
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: nodejs-cronjob
          labels:
            name: nodejs-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs-cronjob
              image: khannedy/nodejs-job

# kubectl apply -f 16-cron-job.yaml

# kubectl get cronjobs
# kubectl describe cronjob nodejs-cronjob
# kubectl delete cronjob nodejs-cronjob

# Add label node for node selector
# kubectl label node minikube key=value

# get all resource
# kubectl get all
# kubectl get all --namespace kube-system

# remove all resource
# kubectl delete all --all
# kubectl delete all --all --namespace namanamespace