apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
  labels:
    name: my-pod1
spec:
  containers:
  - name: hello-world
    image: adamstudiodocker/udemy-praktis-belajar-docker-dan-kubernetes-untuk-pemula:hello-world
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"

# 2. Command apply pod:
# kuebctl apply -f 2-create-pod.yaml

# 4. Command menampilkan semua deployment/pod
# kubectl get deployments
# kubectl get pod

# 3. Command menampilkan detail pod dan deployment:
# kubectl describe pod <nama-pod>
# kubectl describe deployment <nama-deployment>

# 5. delete pod
# kubectl delete pod my-pod1