apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: container-mariadb
        image: mariadb:latest
        args:
          - --init file
          - /shared-files/4-schema.sql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-credentials
                key: mysql-root-password
          - name: MYSQL_ROOT_HOST
            value: "%"
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
          - name: root
            mountPath: /shared-files
      volumes:
        - name: db-data
          hostPath:
            path: /data/volume-example
        - name: root
          hostPath:
            path: /
